// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movimientos.DAL.EFCore;

#nullable disable

namespace Movimientos.DAL.EFCore.Migrations
{
    [DbContext(typeof(MovimientosDbContext))]
    [Migration("20220402202201_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Movimientos.COMMON.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<short>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<short>("Genero")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Identificacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<long>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e381eb3-b59a-4354-bdf5-d05829cc3bfe"),
                            Contraseña = "123456789",
                            Direccion = "Psje. Limatambo 121, Tarapoto, San Martín, San Martín, Perú",
                            Edad = (short)27,
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 4, 2, 15, 22, 1, 454, DateTimeKind.Local).AddTicks(4095),
                            FechaModificacion = new DateTime(2022, 4, 2, 15, 22, 1, 454, DateTimeKind.Local).AddTicks(4096),
                            Genero = (short)1,
                            Identificacion = 73215945L,
                            Nombre = "Gustavo Gavancho León",
                            Telefono = 946585141L
                        });
                });

            modelBuilder.Entity("Movimientos.COMMON.Models.Cuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<long>("NumeroCuenta")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<short>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cuenta");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0bb27fe1-5fe2-4769-bf2f-94f052dad382"),
                            ClienteId = new Guid("6e381eb3-b59a-4354-bdf5-d05829cc3bfe"),
                            Estado = true,
                            FechaCreacion = new DateTime(2022, 4, 2, 15, 22, 1, 454, DateTimeKind.Local).AddTicks(4219),
                            FechaModificacion = new DateTime(2022, 4, 2, 15, 22, 1, 454, DateTimeKind.Local).AddTicks(4220),
                            NumeroCuenta = 130195L,
                            SaldoInicial = 2000m,
                            Tipo = (short)1
                        });
                });

            modelBuilder.Entity("Movimientos.COMMON.Models.Movimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<short>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("Movimientos.COMMON.Models.Cuenta", b =>
                {
                    b.HasOne("Movimientos.COMMON.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Movimientos.COMMON.Models.Movimiento", b =>
                {
                    b.HasOne("Movimientos.COMMON.Models.Cuenta", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movimientos.COMMON.Models.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
